language: node_js
node_js:
  - '6'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: ./public
  repo: git@github.com:CollaborationInEncapsulation/collaborationinencapsulation.github.io.git
  target_branch: master
  on:
    branch: master
script:
  - npm run lint
  - npm run test
